manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
<<<<<<< HEAD
<<<<<<< HEAD
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
=======
>>>>>>> 5fb3728 (Initial User Config.)
=======
>>>>>>> 8628d72 (first)
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
